name: 'Terraform'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Terraform/**'
  pull_request:
    paths:
      - 'Terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: Terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ACI }}
          tenant-id: ${{ secrets.ATI }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # or your preferred version

      - name: Terraform Init with backend config
        run: |
          terraform init \
            -backend-config="resource_group_name=storageaccount" \
            -backend-config="storage_account_name=terraformstatejb" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=dev.terraform.tfstate"

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"

      # Uncomment this to apply changes
      # - name: Terraform Apply
      #   run: terraform apply -var-file="dev.tfvars" -auto-approve

      # Comment this out if you don't want to destroy resources
      - name: Terraform Destroy
        run: terraform destroy -var-file="dev.tfvars" -auto-approve
